#!/bin/bash

COUNTER=20
until [ $COUNTER -lt 10 ]; do
  `echo 0=40% > /dev/servoblaster`
   sleep .25
  `echo 0=-40% > /dev/servoblaster`
   sleep .5
   echo COUNTER $COUNTER
   let COUNTER-=1 
done

