#!/bin/bash

# library used: ServoBlaster (https://github.com/richardghirst/PiBits/tree/master/ServoBlaster)


COUNTER=20
until [ $COUNTER -lt 10 ]; do
   #Servo on GPIO-4
  `echo 0=40% > /dev/servoblaster`
   sleep .25
  `echo 0=-40% > /dev/servoblaster`
   sleep .5

   #Servo on GPIO-17
  `echo 1=40% > /dev/servoblaster`
   sleep .25
  `echo 1=-40% > /dev/servoblaster`
   sleep .5


   #Servo on GPIO-18
  `echo 2=40% > /dev/servoblaster`
   sleep .25
  `echo 2=-40% > /dev/servoblaster`
   sleep .5


   echo COUNTER $COUNTER
   let COUNTER-=1 
done

